// Autogenerated from Pigeon (v0.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FPNIosDidRegisterRequest;

@interface FPNIosDidRegisterRequest : NSObject
@property(nonatomic, copy, nullable) NSString * deviceTokenBase64;
@end

@protocol FPNFlutterPushNotificationHostApi
-(void)iosRegisterForRemoteNotifications:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FPNFlutterPushNotificationHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FPNFlutterPushNotificationHostApi> _Nullable api);

@interface FPNFlutterPushNotificationFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)iosDidRegister:(FPNIosDidRegisterRequest*)input completion:(void(^)(NSError* _Nullable))completion;
- (void)iosFailedRegister:(void(^)(NSError* _Nullable))completion;
@end
NS_ASSUME_NONNULL_END
