// Autogenerated from Pigeon (v0.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FPNIosDidRegisterCallbackArg;

@interface FPNIosDidRegisterCallbackArg : NSObject
@property(nonatomic, strong, nullable) NSNumber * success;
@property(nonatomic, copy, nullable) NSString * deviceToken;
@property(nonatomic, copy, nullable) NSString * errorMessage;
@end

@protocol FPNFlutterPushNotificationHostApi
-(void)iosRegister:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FPNFlutterPushNotificationHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FPNFlutterPushNotificationHostApi> _Nullable api);

@interface FPNFlutterPushNotificationFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)iosRegisterCallback:(FPNIosDidRegisterCallbackArg*)input completion:(void(^)(NSError* _Nullable))completion;
@end
NS_ASSUME_NONNULL_END
