// Autogenerated from Pigeon (v0.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import
import 'dart:async';
import 'package:flutter/services.dart';

class IosDidRegisterCallbackArg {
  bool success;
  String deviceToken;
  String errorMessage;
  // ignore: unused_element
  Map<dynamic, dynamic> _toMap() {
    final Map<dynamic, dynamic> pigeonMap = <dynamic, dynamic>{};
    pigeonMap['success'] = success;
    pigeonMap['deviceToken'] = deviceToken;
    pigeonMap['errorMessage'] = errorMessage;
    return pigeonMap;
  }
  // ignore: unused_element
  static IosDidRegisterCallbackArg _fromMap(Map<dynamic, dynamic> pigeonMap) {
    if (pigeonMap == null){
      return null;
    }
    final IosDidRegisterCallbackArg result = IosDidRegisterCallbackArg();
    result.success = pigeonMap['success'];
    result.deviceToken = pigeonMap['deviceToken'];
    result.errorMessage = pigeonMap['errorMessage'];
    return result;
  }
}

class FlutterPushNotificationHostApi {
  Future<void> iosRegister() async {
    const BasicMessageChannel<dynamic> channel =
        BasicMessageChannel<dynamic>('dev.flutter.pigeon.FlutterPushNotificationHostApi.iosRegister', StandardMessageCodec());
    
    final Map<dynamic, dynamic> replyMap = await channel.send(null);
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null);
    } else if (replyMap['error'] != null) {
      final Map<dynamic, dynamic> error = replyMap['error'];
      throw PlatformException(
          code: error['code'],
          message: error['message'],
          details: error['details']);
    } else {
      // noop
    }
    
  }
}

abstract class FlutterPushNotificationFlutterApi {
  void iosRegisterCallback(IosDidRegisterCallbackArg arg);
  static void setup(FlutterPushNotificationFlutterApi api) {
    {
      const BasicMessageChannel<dynamic> channel =
          BasicMessageChannel<dynamic>('dev.flutter.pigeon.FlutterPushNotificationFlutterApi.iosRegisterCallback', StandardMessageCodec());
      channel.setMessageHandler((dynamic message) async {
        final Map<dynamic, dynamic> mapMessage = message as Map<dynamic, dynamic>;
        final IosDidRegisterCallbackArg input = IosDidRegisterCallbackArg._fromMap(mapMessage);
        api.iosRegisterCallback(input);
      });
    }
  }
}

