// Autogenerated from Pigeon (v0.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.rzzsdxx.flutter_push_notification;

import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.StandardMessageCodec;
import java.util.ArrayList;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings("unused")
public class Messages {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class IosDidRegisterCallbackArg {
    private Boolean success;
    public Boolean getSuccess() { return success; }
    public void setSuccess(Boolean setterArg) { this.success = setterArg; }

    private String deviceToken;
    public String getDeviceToken() { return deviceToken; }
    public void setDeviceToken(String setterArg) { this.deviceToken = setterArg; }

    private String errorMessage;
    public String getErrorMessage() { return errorMessage; }
    public void setErrorMessage(String setterArg) { this.errorMessage = setterArg; }

    HashMap toMap() {
      HashMap<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("success", success);
      toMapResult.put("deviceToken", deviceToken);
      toMapResult.put("errorMessage", errorMessage);
      return toMapResult;
    }
    static IosDidRegisterCallbackArg fromMap(HashMap map) {
      IosDidRegisterCallbackArg fromMapResult = new IosDidRegisterCallbackArg();
      Object success = map.get("success");
      fromMapResult.success = (Boolean)success;
      Object deviceToken = map.get("deviceToken");
      fromMapResult.deviceToken = (String)deviceToken;
      Object errorMessage = map.get("errorMessage");
      fromMapResult.errorMessage = (String)errorMessage;
      return fromMapResult;
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface FlutterPushNotificationHostApi {
    void iosRegister();

    /** Sets up an instance of `FlutterPushNotificationHostApi` to handle messages through the `binaryMessenger` */
    static void setup(BinaryMessenger binaryMessenger, FlutterPushNotificationHostApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.FlutterPushNotificationHostApi.iosRegister", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            HashMap<String, HashMap> wrapped = new HashMap<>();
            try {
              api.iosRegister();
              wrapped.put("result", null);
            }
            catch (Exception exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }

  /** Generated class from Pigeon that represents Flutter messages that can be called from Java.*/
  public static class FlutterPushNotificationFlutterApi {
    private final BinaryMessenger binaryMessenger;
    public FlutterPushNotificationFlutterApi(BinaryMessenger argBinaryMessenger){
      this.binaryMessenger = argBinaryMessenger;
    }
    public interface Reply<T> {
      void reply(T reply);
    }
    public void iosRegisterCallback(IosDidRegisterCallbackArg argInput, Reply<Void> callback) {
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.FlutterPushNotificationFlutterApi.iosRegisterCallback", new StandardMessageCodec());
      HashMap inputMap = argInput.toMap();
      channel.send(inputMap, channelReply -> {
        callback.reply(null);
      });
    }
  }
  private static HashMap wrapError(Exception exception) {
    HashMap<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", null);
    errorMap.put("details", null);
    return errorMap;
  }
}
